### ISSUE TITLE
Reprendre l'architecture de la base de données

### ISSUE THREAD

**Issue by adricen** [Ma6Tvacoder-Docs/ExercicesPHP#5]
- [x] Reprendre l'architecture de la base de données et ajouter une colonne nom

Afin de permettre de retrouver le nom de l'image il serait bien d'ajouter une colonne nom afin de pouvoir identifier les elements et a qui ils appartiennent

**Comment by Gootime** [comment]
ajout de la colonne nom

**Comment by Gootime** [comment]
done

**Comment by adricen** [comment]
Ok super, 

je n'ai pas encore eu le temps d'en faire faire le tour mais le rendus est top pour le moment.

Thx
